-- ============================================================================
-- THE ISLE / AURA: COMPLETE SCHEMA REBUILD
-- Drops existing tables and recreates them with correct columns and schemas.
-- ============================================================================

-- Drop tables if they exist to start completely fresh
DROP TABLE IF EXISTS public.bot_config CASCADE;
DROP TABLE IF EXISTS public.player_links CASCADE;
DROP TABLE IF EXISTS public.server_roles CASCADE;
DROP TABLE IF EXISTS public.player_marks CASCADE;
DROP TABLE IF EXISTS public.command_cooldowns CASCADE;
DROP TABLE IF EXISTS public.transaction_logs CASCADE;
DROP TABLE IF EXISTS public.player_storage_limits CASCADE;
DROP TABLE IF EXISTS public.player_storage CASCADE;
DROP TABLE IF EXISTS public.player_skin_storage CASCADE;
DROP TABLE IF EXISTS public.player_stats CASCADE;
DROP TABLE IF EXISTS public.rcon_console_logs CASCADE;
DROP TABLE IF EXISTS public.user_skins CASCADE;
DROP TABLE IF EXISTS public.dino_skins CASCADE;
DROP TABLE IF EXISTS public.store_products CASCADE;
DROP TABLE IF EXISTS public.store_purchases CASCADE;
DROP TABLE IF EXISTS public.economy_rates CASCADE;
DROP TABLE IF EXISTS public.dino_tiers CASCADE;
DROP TABLE IF EXISTS public.live_map_positions CASCADE;
DROP TABLE IF EXISTS public.pending_tasks CASCADE;

-- 1. Bot Configuration
-- Key-value stores for bot parameters
CREATE TABLE public.bot_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 2. Discord & Steam Linking
-- Maps Discord account identifiers to 17-digit Steam IDs
CREATE TABLE public.player_links (
    discord_id BIGINT PRIMARY KEY,
    steam_id TEXT NOT NULL UNIQUE,
    discord_username TEXT,
    linked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Staff Roles (For Discord Permissions)
-- Marks admin or moderator privileges by Discord account
CREATE TABLE public.server_roles (
    discord_id BIGINT PRIMARY KEY,
    is_admin BOOLEAN DEFAULT false,
    is_mod BOOLEAN DEFAULT false
);

-- 4. Economy & Leveling Core (Marks, XP, Kills, and Violations)
-- Holds balances, stats, strikes, and violations
CREATE TABLE public.player_marks (
    steam_id TEXT PRIMARY KEY,
    marks BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    xp BIGINT DEFAULT 0,
    total_xp BIGINT DEFAULT 0,
    kills INTEGER DEFAULT 0,
    free_teleports INTEGER DEFAULT 0,
    last_daily TIMESTAMP WITH TIME ZONE,
    last_reward TIMESTAMP WITH TIME ZONE,
    debt_owed INTEGER DEFAULT 0,
    strikes INTEGER DEFAULT 0,
    last_violation TIMESTAMP WITH TIME ZONE,
    permabanned BOOLEAN DEFAULT false,
    rule_violations INTEGER DEFAULT 0,
    total_fines INTEGER DEFAULT 0,
    last_fine_reason TEXT
);

-- 5. Command Cooldowns
-- Throttles commands to prevent exploitation
CREATE TABLE public.command_cooldowns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    steam_id TEXT NOT NULL,
    command_name TEXT NOT NULL,
    last_used TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(steam_id, command_name)
);

-- 6. Economy Logs (Audit Trail)
-- Logs every transaction for audits
CREATE TABLE public.transaction_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    steam_id TEXT NOT NULL,
    recipient_steam TEXT,
    command_name TEXT NOT NULL,
    amount BIGINT NOT NULL,
    action TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Storage System: Limits
CREATE TABLE public.player_storage_limits (
    steam_id TEXT PRIMARY KEY,
    max_dino_slots INTEGER NOT NULL DEFAULT 1,
    max_skin_slots INTEGER NOT NULL DEFAULT 5
);

-- 8. Storage System: Dinos
CREATE TABLE public.player_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id TEXT NOT NULL,
    name TEXT NOT NULL,
    raw_data TEXT NOT NULL,
    skin_data TEXT,
    stored_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Storage System: Skins
CREATE TABLE public.player_skin_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id TEXT NOT NULL,
    name TEXT NOT NULL,
    skin_data TEXT NOT NULL,
    stored_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Custom Player Stats (Hunger, Thirst, Poison, etc)
CREATE TABLE public.player_stats (
    steam_id TEXT PRIMARY KEY,
    hunger FLOAT DEFAULT 0,
    thirst FLOAT DEFAULT 0,
    stamina FLOAT DEFAULT 0,
    blood FLOAT DEFAULT 0,
    carb FLOAT DEFAULT 0,
    lipid FLOAT DEFAULT 0,
    protein FLOAT DEFAULT 0,
    poison FLOAT DEFAULT 0,
    infection FLOAT DEFAULT 0,
    temperature FLOAT DEFAULT 0,
    fatigue FLOAT DEFAULT 0
);

-- 11. RCON Logs
CREATE TABLE public.rcon_console_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. User Skins
CREATE TABLE public.user_skins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    steam_id TEXT NOT NULL,
    skin_data TEXT NOT NULL,
    skin_name TEXT,
    passcode TEXT UNIQUE,
    skin_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 13. Dino Skins
CREATE TABLE public.dino_skins (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    steam_id TEXT NOT NULL,
    dino_class TEXT NOT NULL,
    skin_code TEXT NOT NULL,
    skin_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 14. Store Products
CREATE TABLE public.store_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    price BIGINT NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 15. Store Purchases
CREATE TABLE public.store_purchases (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    steam_id TEXT NOT NULL,
    product_id UUID NOT NULL,
    price_paid BIGINT NOT NULL,
    purchased_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 16. Economy/Mark Multiplier Rates
CREATE TABLE public.economy_rates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    rate_name TEXT NOT NULL UNIQUE,
    multiplier FLOAT DEFAULT 1.0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 17. Dino Tiers (Allowed in Skin Creator)
CREATE TABLE public.dino_tiers (
    dino_id TEXT PRIMARY KEY,
    tier INTEGER DEFAULT 1
);

-- 18. Live Map Coordinates
CREATE TABLE public.live_map_positions (
    steam_id TEXT PRIMARY KEY,
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    player_name TEXT NOT NULL,
    species TEXT NOT NULL,
    health FLOAT NOT NULL,
    growth FLOAT NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 19. Pending Tasks Queue
CREATE TABLE public.pending_tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    command TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create Indexes for fast retrieval
CREATE INDEX IF NOT EXISTS idx_user_skins_passcode ON public.user_skins(passcode);
CREATE INDEX IF NOT EXISTS idx_user_skins_skin_hash ON public.user_skins(skin_hash);
CREATE INDEX IF NOT EXISTS idx_dino_skins_steam_id ON public.dino_skins(steam_id);

-- Disable Row Level Security (RLS) or Enable as needed.
-- Since the bots bypass RLS with their service key, we can enable RLS on all tables.
ALTER TABLE public.bot_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.server_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.command_cooldowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_storage_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_storage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_skin_storage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rcon_console_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_skins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dino_skins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.economy_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dino_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_map_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_tasks ENABLE ROW LEVEL SECURITY;
