Config = Config or {}

Config.Tutorials = {
    -- =====================================================================
    -- POLICE
    -- =====================================================================
    ['police'] = {
        label = 'Houston PD Field Training',
        jobRequired = 'police',
        mentorModel = 's_m_m_snowcop_01',
        mentorCoords = vec4(441.0, -980.0, 30.0, 90.0),
        reward = 500,
        phases = {
            {
                title = 'Welcome to HPD',
                dialogue = 'Welcome to Houston PD, recruit. This is the finest department in Texas. I\'m gonna walk you through the basics — by the end, you\'ll know how to cuff, jail, and file reports. Ready?',
                objective = 'Listen to your training sergeant.',
                waypoint = nil,
                keybinds = nil,
                completeOn = 'timer',
                completeTime = 8000,
            },
            {
                title = 'Arrest a Suspect',
                dialogue = 'See that troublemaker by the cruiser? Go cuff him — press E when targeting him, then G to escort. Once he\'s in cuffs, take him to the jail cell and use /jail [ID] 5.',
                objective = 'Cuff the suspect, then jail them for 5 minutes.',
                waypoint = vec3(445.0, -985.0, 29.0),
                keybinds = 'E → Cuff | G → Escort | /jail [ID] [minutes]',
                completeOn = 'command',
                completeCommand = 'jail',
            },
            {
                title = 'File Your Report',
                dialogue = 'Every arrest needs paperwork. Use /uofreport to document what just happened. Fill in the details and submit — it goes straight to the department Discord. Now you\'re ready for patrol. Stay safe out there.',
                objective = 'Open /uofreport and file a use-of-force report.',
                waypoint = nil,
                keybinds = '/uofreport → Open incident report form',
                completeOn = 'command',
                completeCommand = 'uofreport',
            },
        },
    },
    ['sasp'] = {
        label = 'Texas DPS Highway Patrol',
        jobRequired = 'sasp',
        mentorModel = 's_m_m_highsec_02',
        mentorCoords = vec4(1855.0, 3690.0, 34.0, 210.0),
        reward = 500,
        phases = {
            {
                title = 'Texas DPS Welcome',
                dialogue = 'Trooper, welcome to the Texas Department of Public Safety. Our jurisdiction is the open road. Highways, state routes, and rural counties — that\'s our beat. Let\'s get you trained up.',
                objective = 'Listen to your trooper mentor.',
                completeOn = 'timer',
                completeTime = 6000,
            },
            {
                title = 'Speed Enforcement',
                dialogue = 'Pull over that speeder on the highway. Use /plate to scan their tags, then cuff and cite them. DPS handles thousands of traffic stops — get good at this.',
                objective = 'Scan a plate with /plate, then cuff the driver.',
                waypoint = vec3(1860.0, 3685.0, 33.0),
                keybinds = '/plate [plate] → Scan plate | E → Cuff',
                completeOn = 'command',
                completeCommand = 'cuff',
            },
            {
                title = 'Spike Strip Deployment',
                dialogue = 'Pursuits end with spike strips. Deploy one now — press your spike strip hotkey or use the interaction menu. Place it on the road ahead of a fleeing vehicle. Good work, trooper.',
                objective = 'Deploy a spike strip on the road.',
                waypoint = nil,
                keybinds = 'F9 → Interact → Place Spike Strip',
                completeOn = 'command',
                completeCommand = 'spike',
            },
        },
    },
    ['fib'] = {
        label = 'FIB Special Agent Training',
        jobRequired = 'fib',
        mentorModel = 's_m_m_fiboffice_01',
        mentorCoords = vec4(140.0, -740.0, 250.0, 0.0),
        reward = 750,
        phases = {
            {
                title = 'Federal Bureau',
                dialogue = 'Agent, welcome to the Federal Investigation Bureau. We handle what local PD can\'t — organized crime, bank heists, hijackings, and federal warrants. Your tools: evidence collection and federal authority.',
                objective = 'Listen to your director.',
                completeOn = 'timer',
                completeTime = 7000,
            },
            {
                title = 'Evidence Collection',
                dialogue = 'A crime scene is nearby. Collect shell casings and fingerprints. Use /evidence to open the collection menu, then tag each piece. Everything goes into the MDT for prosecution.',
                objective = 'Use /evidence to collect shell casings.',
                waypoint = vec3(145.0, -745.0, 248.0),
                keybinds = '/evidence → Open forensic menu',
                completeOn = 'command',
                completeCommand = 'evidence',
            },
            {
                title = 'Federal Seizure',
                dialogue = 'When you have probable cause, you can seize assets. Use /federal on a suspect to flag them, then /seize to confiscate weapons and contraband. You\'re now authorized for field operations.',
                objective = 'Use /federal then /seize on the target.',
                keybinds = '/federal [ID] → Flag federal | /seize → Confiscate',
                completeOn = 'command',
                completeCommand = 'seize',
            },
        },
    },
    -- =====================================================================
    -- EMS
    -- =====================================================================
    ['ambulance'] = {
        label = 'Texas EMS First Response',
        jobRequired = 'ambulance',
        mentorModel = 's_m_m_paramedic_01',
        mentorCoords = vec4(305.0, -600.0, 43.0, 160.0),
        reward = 500,
        phases = {
            {
                title = 'EMS Welcome',
                dialogue = 'Welcome to Texas EMS. When someone\'s down, we\'re the ones who get them back up. Quick response, clear communication, and proper procedure save lives. Let\'s run through it.',
                objective = 'Listen to the chief paramedic.',
                completeOn = 'timer',
                completeTime = 6000,
            },
            {
                title = 'Revive a Patient',
                dialogue = 'There\'s a patient down across the street. Get to them, assess the situation, and use /revive. Make sure the area is secure first — you can\'t help anyone if you\'re down too.',
                objective = 'Find the injured NPC and use /revive on them.',
                waypoint = vec3(310.0, -590.0, 43.0),
                keybinds = '/revive → Revive downed player (must be next to them)',
                completeOn = 'command',
                completeCommand = 'revive',
            },
            {
                title = 'Hospital Transport',
                dialogue = 'Now transport the patient to Pillbox Hospital. Use /checkin when you arrive at the ER bay. The hospital staff will take over from there. You\'re cleared for duty — stay sharp.',
                objective = 'Check in the patient at Pillbox Hospital.',
                waypoint = vec3(308.0, -595.0, 43.0),
                keybinds = '/checkin → Admit patient to hospital',
                completeOn = 'command',
                completeCommand = 'checkin',
            },
        },
    },
    -- =====================================================================
    -- CIVILIAN
    -- =====================================================================
    ['lumberjack'] = {
        label = 'Piney Woods Logging',
        jobRequired = 'lumberjack',
        mentorModel = 's_m_y_construct_01',
        mentorCoords = vec4(-540.0, 5350.0, 70.0, 45.0),
        reward = 300,
        phases = {
            {
                title = 'Welcome to the Woods',
                dialogue = 'Howdy, greenhorn. Welcome to Piney Woods Logging Co. We supply timber to all of H-Town. Grab your axe — here\'s how it works.',
                objective = 'Listen to your foreman.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'Chop a Tree',
                dialogue = 'See that marked pine? Walk up to it and use /choptree. You\'ll get a minigame — hit the target circle when the marker swings into the green zone. Accuracy gets you more XP.',
                objective = 'Use /choptree on the marked tree and complete the minigame.',
                waypoint = vec3(-545.0, 5355.0, 70.0),
                keybinds = '/choptree → Start axe minigame | Click when marker in green',
                completeOn = 'command',
                completeCommand = 'choptree',
            },
            {
                title = 'Load and Deliver',
                dialogue = 'Good swing! Now gather those logs. Use /loadlogs to stack them in your truck, then drive to the Killeen Sawmill. Crew up with /joincrew to earn bonus XP. You\'re a logger now.',
                objective = 'Load logs into your truck.',
                keybinds = '/loadlogs → Load wood | /joincrew [ID] → Team up',
                completeOn = 'command',
                completeCommand = 'loadlogs',
            },
        },
    },
    ['trucking'] = {
        label = 'Lone Star Logistics',
        jobRequired = 'trucker',
        mentorModel = 's_m_m_trucker_01',
        mentorCoords = vec4(900.0, -180.0, 74.0, 90.0),
        reward = 400,
        phases = {
            {
                title = 'Killeen Distribution Center',
                dialogue = 'Welcome to Lone Star Logistics, driver. We move freight across Texas — Houston to Ft. Worth, Galveston to Killeen. Four routes, four pay grades. Here\'s your rig.',
                objective = 'Listen to the fleet manager.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'Pick Your Route',
                dialogue = 'Use /truckroute to see available runs. Select the Gulf Coast Run to start — it\'s the easiest. Each route pays based on distance. The truck is waiting outside.',
                objective = 'Use /truckroute to view and select a route.',
                keybinds = '/truckroute → View routes | /loadcargo → Load freight',
                completeOn = 'command',
                completeCommand = 'truckroute',
            },
            {
                title = 'Load and Roll',
                dialogue = 'Load your cargo with /loadcargo. Follow the GPS waypoint to your destination. Park in the delivery zone to complete the run. Longer routes pay more — work your way up to Panhandle Express.',
                objective = 'Load cargo and start your first run.',
                keybinds = '/loadcargo → Load truck',
                completeOn = 'command',
                completeCommand = 'loadcargo',
            },
        },
    },
    ['carwash'] = {
        label = 'Texas Suds Car Wash',
        jobRequired = 'carwash',
        mentorModel = 's_m_y_busboy_01',
        mentorCoords = vec4(50.0, -1390.0, 29.0, 0.0),
        reward = 300,
        phases = {
            {
                title = 'Welcome to Texas Suds',
                dialogue = 'Welcome to Texas Suds, partner! We got three tiers: Basic Rinse, Texas Two-Step, and Lone Star Supreme. You start at the bottom — work your way up. Use /startshift to clock in.',
                objective = 'Listen to the manager.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'First Wash',
                dialogue = 'Pull a car into the bay and use /wash. You\'ll get the pressure washer — aim at the dirt spots and hold the trigger. Each tier cleans more thoroughly and pays better.',
                objective = 'Wash a car using /wash in the wash bay.',
                waypoint = vec3(55.0, -1390.0, 29.0),
                keybinds = '/wash → Start washing | Hold LMB to spray',
                completeOn = 'command',
                completeCommand = 'wash',
            },
            {
                title = 'Check the Boss Panel',
                dialogue = 'When you\'re ready to run your own location, use /bossmenu. You can hire NPCs, manage supplies, and track sales. Now get back to work — cars ain\'t gonna wash themselves.',
                objective = 'Open the boss panel with /bossmenu.',
                keybinds = '/bossmenu → Business management | /startshift → Clock in',
                completeOn = 'command',
                completeCommand = 'bossmenu',
            },
        },
    },
    ['oiljob'] = {
        label = 'Texas Crude Co.',
        jobRequired = 'oiljob',
        mentorModel = 's_m_y_construct_02',
        mentorCoords = vec4(2700.0, 2900.0, 38.0, 180.0),
        reward = 500,
        phases = {
            {
                title = 'Oil Field Welcome',
                dialogue = 'Welcome to Texas Crude, roughneck. This is the Killeen oil field. Hard work, good pay. Grab your hardhat — let\'s learn the drill.',
                objective = 'Listen to your rig manager.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'Operate the Drill',
                dialogue = 'Head to the rig and use /drill. You\'ll control the drill depth — keep it in the sweet spot. Too shallow, no oil. Too deep, equipment damage. Get it right for max yield.',
                objective = 'Use /drill at the oil rig and hit the sweet spot.',
                waypoint = vec3(2710.0, 2905.0, 38.0),
                keybinds = '/drill → Start drilling | /pump → Extract oil',
                completeOn = 'command',
                completeCommand = 'drill',
            },
            {
                title = 'Crew Bonus',
                dialogue = 'Oil is a team sport. Use /joincrew to partner up — crew members get bonus pay when the rig is running. Now get back to work before the field supervisor notices.',
                objective = 'Use /pump to start extraction.',
                keybinds = '/pump → Start pump | /joincrew [ID] → Team bonus',
                completeOn = 'command',
                completeCommand = 'pump',
            },
        },
    },
    -- =====================================================================
    -- CRIMINAL (guidelines)
    -- =====================================================================
    ['dealing'] = {
        label = 'Street Dealer Network',
        jobRequired = nil,
        mentorModel = 'g_m_y_famdnf_01',
        mentorCoords = vec4(94.0, -1730.0, 29.0, 320.0),
        reward = 200,
        phases = {
            {
                title = 'The Street Game',
                dialogue = 'Listen close. I\'m only gonna say this once. The streets run on supply and demand. You got product, you find a buyer. You got territory, you protect it. Simple. Complicated gets you dead.',
                objective = 'Listen to the dealer.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'Find Your Market',
                dialogue = 'Drug spots cycle every two hours. Use /drugspots to see what\'s active. Different zones have different buyers — Third Ward moves weed, Montrose buys coke. Know your market.',
                objective = 'Use /drugspots to view active drug spots.',
                keybinds = '/drugspots → View active spots | /deal [id] → Sell to buyer',
                completeOn = 'command',
                completeCommand = 'drugspots',
            },
            {
                title = 'The Rules',
                dialogue = 'Three rules. One: dirty money goes through businesses. Two: never sell on another crew\'s territory without permission. Three: if the cops show up, you were never here. Good luck, hustler.',
                objective = 'Complete street wisdom.',
                completeOn = 'timer',
                completeTime = 6000,
            },
        },
    },
    ['racing'] = {
        label = 'H-Town Midnight Runs',
        jobRequired = nil,
        mentorModel = 'u_m_y_baygor',
        mentorCoords = vec4(320.0, -110.0, 68.0, 160.0),
        reward = 300,
        phases = {
            {
                title = 'Underground Racing',
                dialogue = 'You wanna race? Five routes across Texas. Galveston Drag, Killeen Dust Sprint, Third Ward Circuit, Ft. Worth Mountain Pass, Bayou Backroads. Muscle cars only. Cash wagers. Rep matters more than money down here.',
                objective = 'Listen to the race organizer.',
                completeOn = 'timer',
                completeTime = 5000,
            },
            {
                title = 'Join a Race',
                dialogue = 'Use /joinrace when a race is forming. You can bet dirty money on yourself. Win races to build reputation — higher rep unlocks more routes. Lose and you\'re out your wager.',
                objective = 'Use /joinrace to enter a race lobby.',
                keybinds = '/joinrace [ID] → Enter race | /startrace → Begin countdown',
                completeOn = 'command',
                completeCommand = 'joinrace',
            },
            {
                title = 'The Leaderboard',
                dialogue = 'Check /raceleaderboard to see where you rank. Top drivers get respect — and challenges from randoms wanting your spot. Keep your car tuned and your reflexes sharp.',
                objective = 'Check the leaderboard.',
                keybinds = '/raceleaderboard → View rankings | /leaverace → Exit',
                completeOn = 'command',
                completeCommand = 'raceleaderboard',
            },
        },
    },
}
