"""Fill missing 5e SRD rule categories in Solis-Grave compendium."""
import psycopg2, json

c = psycopg2.connect('postgresql://postgres:FamiliaAwesome1!@db.yqfzaugbrwoluhkddcsh.supabase.co:5432/postgres')
c.autocommit = True; cur = c.cursor()

rules = [
    # SPELL SCHOOLS
    {"category": "spell_schools", "name": "Abjuration", "description": "Protective magic. Abjuration spells create barriers, banish creatures, or negate harmful effects. Includes spells like Shield, Counterspell, and Dispel Magic.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Conjuration", "description": "Summoning and teleportation magic. Conjuration spells bring creatures, objects, or energy to the caster. Includes Find Familiar, Misty Step, and Teleport.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Divination", "description": "Information-gathering magic. Divination spells reveal secrets, locate objects, or glimpse the future. Includes Detect Magic, Identify, and Scrying.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Enchantment", "description": "Mind-affecting magic. Enchantment spells charm, confuse, or control creatures. Includes Charm Person, Suggestion, and Dominate Monster.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Evocation", "description": "Energy manipulation magic. Evocation spells create elemental effects — fire, lightning, cold, or raw magical force. Includes Fireball, Lightning Bolt, and Magic Missile.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Illusion", "description": "Deceptive magic. Illusion spells create false images, sounds, or sensations. Includes Invisibility, Minor Illusion, and Mirror Image.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Necromancy", "description": "Life and death magic. Necromancy spells manipulate life force, create undead, or drain vitality. In Solis-Grave, Necromancy is illegal under Church law. Includes Animate Dead, False Life, and Finger of Death.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "spell_schools", "name": "Transmutation", "description": "Transformative magic. Transmutation spells change the properties of creatures, objects, or environments. Includes Haste, Polymorph, and Fly.", "source_tags": ["solis-grave","5e","srd"]},

    # CORE COMBAT RULES (missing ones)
    {"category": "combat", "name": "Mounted Combat", "description": "While mounted, you can control a trained mount as a free action. An independent mount acts on its own initiative. If your mount is knocked prone, you can use your reaction to land on your feet (DC 10 Dexterity save). Mounted combat grants advantage on melee attacks against unmounted creatures smaller than your mount.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "combat", "name": "Underwater Combat", "description": "When underwater: creatures without a swim speed have disadvantage on melee weapon attacks (unless using a dagger, javelin, shortsword, spear, or trident). Ranged weapon attacks automatically miss beyond normal range. Fire damage is halved unless the damage source is specifically noted to function underwater. Creatures fully immersed can hold their breath for 1 + CON modifier minutes (minimum 30 seconds).", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "combat", "name": "Damage Resistance and Vulnerability", "description": "If a creature has resistance to a damage type, damage of that type is halved. If a creature has vulnerability, damage is doubled. Multiple instances of resistance or vulnerability do not stack — apply only once. Resistance and vulnerability are applied AFTER all other modifiers to damage.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "combat", "name": "Temporary Hit Points", "description": "Temporary hit points are a buffer of extra hit points. When you have temporary HP and take damage, the temporary HP are lost first. Temporary HP do not stack — if you gain more while you already have some, you keep the higher amount. They last until depleted or until you finish a long rest.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "combat", "name": "Surprise", "description": "If neither side tries to be stealthy, they automatically notice each other. Otherwise, compare Dexterity (Stealth) checks of hiding creatures to passive Wisdom (Perception) of potential observers. Any creature that doesn't notice a threat is surprised at the start of combat. A surprised creature can't move or take actions on its first turn, and can't take reactions until after that turn ends.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "combat", "name": "Ready Action", "description": "You can use your action to Ready an action, specifying a trigger (e.g., 'when the goblin comes through the door') and the action you'll take in response. When the trigger occurs, you can use your reaction to take the readied action. If you ready a spell, you must concentrate on it (as if concentrating on a spell) and the spell slot is expended whether you release it or not.", "source_tags": ["solis-grave","5e","srd"]},

    # MOVEMENT & TRAVEL
    {"category": "exploration", "name": "Travel Pace", "description": "While traveling overland: Fast pace = 400 feet per minute / 4 miles per hour / 30 miles per day, -5 penalty to passive Perception. Normal pace = 300 ft/min / 3 mph / 24 mi/day. Slow pace = 200 ft/min / 2 mph / 18 mi/day, able to use Stealth. Difficult terrain (dense forests, swamps, rubble) halves travel speed.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "exploration", "name": "Falling", "description": "A fall from a height deals 1d6 bludgeoning damage per 10 feet fallen, to a maximum of 20d6. The creature lands prone unless it avoids taking damage from the fall. In Solis-Grave, the Citadel's cliffside location makes falling a constant threat — the chasm beneath the Dragon-Garrison is bottomless per garrison legend.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "exploration", "name": "Suffocating", "description": "A creature can hold its breath for 1 + Constitution modifier minutes (minimum 30 seconds). After that, it can survive for a number of rounds equal to its Constitution modifier (minimum 1). Then it drops to 0 HP and is dying. It can't regain HP or be stabilized until it can breathe again.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "exploration", "name": "Vision and Light", "description": "Bright light lets most creatures see normally. Dim light (shadows, fog, twilight) creates a lightly obscured area — creatures have disadvantage on Wisdom (Perception) checks that rely on sight. Darkness creates a heavily obscured area — creatures effectively suffer the blinded condition. Darkvision allows seeing in darkness as if dim light (no color, shades of gray only). Blindsight allows perceiving without sight within a radius. Truesight sees through illusions, invisibility, and into the Ethereal Plane.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "exploration", "name": "Food and Water", "description": "A character needs 1 pound of food per day. A character can go without food for 3 + Constitution modifier days before suffering exhaustion. A character needs 1 gallon of water per day (2 gallons in hot conditions). Going without water: after 1 day, DC 15 Constitution save or suffer 1 level of exhaustion. The Sulfur Wastes of Solis-Grave double water requirements due to the heat and ash.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "exploration", "name": "Diseases", "description": "In Solis-Grave, common diseases include: Sump-Fever (DC 12 CON save, disadvantage on physical checks for 1d4 days), Crystal-Lung (from prolonged exposure to Aether dust, DC 14 CON save, lose 1d4 max HP until cured), and Blight-Scale (from Abomination wounds, DC 15 CON save, take 1d6 necrotic per hour until magically cured).", "source_tags": ["solis-grave","5e","srd"]},

    # SOCIAL ENCOUNTERS
    {"category": "social", "name": "Persuasion", "description": "Persuasion checks determine whether you can convince a creature to do something through diplomacy, charm, or logical argument. DC is based on the creature's attitude: Friendly (DC 10-15), Neutral (DC 15-20), Hostile (DC 20-30). A hostile creature won't be persuaded to take risks or make sacrifices regardless of the roll.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "social", "name": "Intimidation", "description": "Intimidation checks attempt to coerce through threats of violence, social ruin, or exposure of secrets. Success makes the target cooperative but resentful. In Solis-Grave, Inquisitors and House Obsidian officials have advantage on Intimidation checks due to their legal authority. After a successful intimidation, the target's attitude may permanently worsen.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "social", "name": "Deception", "description": "Deception checks determine whether you can conceal the truth, pass off falsehoods, or maintain a disguise. Contested by Wisdom (Insight). In Solis-Grave, lying to an Inquisitor about your Blood Purity is a capital crime. House Obsidian members have advantage on Insight checks to detect lies.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "social", "name": "Insight", "description": "Insight checks determine whether you can read a creature's true intentions, detect lies, or sense their emotional state. Contested by Charisma (Deception). Passive Insight (10 + Insight modifier) can automatically detect nervousness, dishonesty, or hidden motives without an active check.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "social", "name": "NPC Attitudes", "description": "NPCs have three attitude states: Friendly (willing to help, takes minor risks), Neutral (indifferent, helps if convenient), Hostile (opposes, won't help without extreme pressure). A successful Charisma check can shift attitude by one step. In Solis-Grave, caste differences apply modifiers: an Archon treats a Blank as automatically Hostile unless the Blank has a patron noble.", "source_tags": ["solis-grave","5e","srd"]},

    # SPELLCASTING DETAILS
    {"category": "magic_rules", "name": "Spell Save DC and Attack Modifier", "description": "Spell save DC = 8 + proficiency bonus + spellcasting ability modifier. Spell attack modifier = proficiency bonus + spellcasting ability modifier. In Solis-Grave, the Spell Safety DC (separate from the target's save DC) is calculated as: DC = 20 - (Blood Purity / 5). Both checks apply — first the caster must pass Spell Safety, then the target may make a save against the spell's effect.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "magic_rules", "name": "Spell Slots Per Level", "description": "Full casters (Wizard, Cleric, Druid, Sorcerer) gain spell slots per the standard 5e table: Level 1 has 2 first-level slots, scaling to Level 20 with 4/3/3/3/3/2/2/1/1. Half casters (Paladin, Ranger) progress at half speed. Warlocks use Pact Magic (fewer slots that recharge on short rest). In Solis-Grave, all casters must pass Spell Safety checks for spells of 1st level or higher.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "magic_rules", "name": "Ritual Casting", "description": "Certain spells have the ritual tag. You can cast a ritual version of the spell without expending a spell slot, but the casting time increases by 10 minutes. You must have the spell prepared or known (class-dependent). Wizards can ritual cast any ritual spell in their spellbook without preparing it. In Solis-Grave, ritual casting bypasses the Spell Safety check due to the extended, careful casting process.", "source_tags": ["solis-grave","5e","srd"]},

    # EQUIPMENT PACKS
    {"category": "equipment", "name": "Burglar's Pack", "description": "Standard burglar's pack: backpack, bag of 1,000 ball bearings, 10 feet of string, bell, 5 candles, crowbar, hammer, 10 pitons, hooded lantern, 2 flasks of oil, 5 days rations, tinderbox, waterskin, 50 feet of hempen rope. Cost: 16 GC. Favored by Strider-Garrison scouts and Sump-Runner thieves in Solis-Grave.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Diplomat's Pack", "description": "Diplomat's pack: chest, 2 cases for maps and scrolls, fine clothes, bottle of ink, ink pen, lamp, 2 flasks of oil, 5 sheets of paper, vial of perfume, sealing wax, soap. Cost: 39 GC. In Solis-Grave, House Obsidian diplomats and Church officials carry these.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Dungeoneer's Pack", "description": "Dungeoneer's pack: backpack, crowbar, hammer, 10 pitons, 10 torches, tinderbox, 10 days rations, waterskin, 50 feet hempen rope. Cost: 12 GC. Standard issue for Citadel cadets entering the lower training depths.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Explorer's Pack", "description": "Explorer's pack: backpack, bedroll, mess kit, tinderbox, 10 torches, 10 days rations, waterskin, 50 feet hempen rope. Cost: 10 GC. Common among House Ferrum border scouts and Core-Thief expeditioners.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Priest's Pack", "description": "Priest's pack: backpack, blanket, 10 candles, tinderbox, alms box, 2 blocks of incense, censer, vestments, 2 days rations, waterskin. Cost: 19 GC. Standard issue for Ordained cadets and Church Inquisitor trainees.", "source_tags": ["solis-grave","5e","srd"]},

    # TOOLS
    {"category": "equipment", "name": "Thieves' Tools", "description": "Thieves' tools include a small file, a set of lock picks, a small mirror mounted on a metal handle, a set of narrow-bladed scissors, and a pair of pliers. Proficiency allows you to add your proficiency bonus to ability checks made to disarm traps or open locks. Cost: 25 GC, Weight: 1 lb. In Solis-Grave, possession without a registered trade license is grounds for Inquisitorial investigation.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Herbalism Kit", "description": "Herbalism kit contains pouches of herbs, clippers, leather gloves, mortar and pestle, and glass jars. Used to identify plants and create antitoxins and healing potions. Cost: 5 GC, Weight: 3 lbs. Sump-Bloods are naturally adept with herbalism, even without formal training.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Poisoner's Kit", "description": "Poisoner's kit includes glass vials, mortar and pestle, chemicals, and a stirring rod. Used to create, apply, and handle poisons. Cost: 50 GC. In Solis-Grave, unlicensed possession is a capital crime in House Obsidian territories. Core-Thieves and Cult operatives use these extensively.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Disguise Kit", "description": "Disguise kit contains cosmetics, hair dye, small props, and a few pieces of clothing. Used to create visual disguises. Cost: 25 GC, Weight: 3 lbs. In Solis-Grave, Ash-Walkers use these to hide their distinctive ashen skin when traveling through Church territories.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Forgery Kit", "description": "Forgery kit includes different types of ink, papers, seals, silver and gold leaf, and small tools to duplicate official documents. Cost: 15 GC, Weight: 5 lbs. In Solis-Grave, forging a Blood Purity certificate or House Obsidian judicial seal carries a sentence of public execution.", "source_tags": ["solis-grave","5e","srd"]},

    # WEAPONS REFERENCE
    {"category": "equipment", "name": "Simple Melee Weapons", "description": "Club (1d4 bludgeoning, light), Dagger (1d4 piercing, finesse, light, thrown 20/60), Greatclub (1d8 bludgeoning, two-handed), Handaxe (1d6 slashing, light, thrown 20/60), Javelin (1d6 piercing, thrown 30/120), Light Hammer (1d4 bludgeoning, light, thrown 20/60), Mace (1d6 bludgeoning), Quarterstaff (1d6 bludgeoning, versatile 1d8), Sickle (1d4 slashing, light), Spear (1d6 piercing, thrown 20/60, versatile 1d8). In Solis-Grave: re-flavored per House origin.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Simple Ranged Weapons", "description": "Light Crossbow (1d8 piercing, ammunition 80/320, loading, two-handed), Dart (1d4 piercing, finesse, thrown 20/60), Shortbow (1d6 piercing, ammunition 80/320, two-handed), Sling (1d4 bludgeoning, ammunition 30/120). In Solis-Grave: House Vortex manufactures crossbows with wind-dampening stocks.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Martial Melee Weapons", "description": "Battleaxe (1d8 slashing, versatile 1d10), Flail (1d8 bludgeoning), Glaive (1d10 slashing, heavy, reach, two-handed), Greataxe (1d12 slashing, heavy, two-handed), Greatsword (2d6 slashing, heavy, two-handed), Halberd (1d10 slashing, heavy, reach, two-handed), Lance (1d12 piercing, reach, special), Longsword (1d8 slashing, versatile 1d10), Maul (2d6 bludgeoning, heavy, two-handed), Morningstar (1d8 piercing), Pike (1d10 piercing, heavy, reach, two-handed), Rapier (1d8 piercing, finesse), Scimitar (1d6 slashing, finesse, light), Shortsword (1d6 piercing, finesse, light), Trident (1d6 piercing, thrown 20/60, versatile 1d8), War Pick (1d8 piercing), Warhammer (1d8 bludgeoning, versatile 1d10), Whip (1d4 slashing, finesse, reach). In Solis-Grave: each weapon forged by a specific House.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Martial Ranged Weapons", "description": "Blowgun (1 piercing, ammunition 25/100, loading), Hand Crossbow (1d6 piercing, ammunition 30/120, light, loading), Heavy Crossbow (1d10 piercing, ammunition 100/400, heavy, loading, two-handed), Longbow (1d8 piercing, ammunition 150/600, heavy, two-handed). In Solis-Grave: House Vortex manufactures the finest bows. Deep-Bloods favor the longbow.", "source_tags": ["solis-grave","5e","srd"]},

    # ARMOR REFERENCE
    {"category": "equipment", "name": "Light Armor", "description": "Padded (AC 11 + DEX, stealth disadvantage), Leather (AC 11 + DEX), Studded Leather (AC 12 + DEX). In Solis-Grave: House Vortex crafts studded leather with aerodynamic studs for sky-scouts. Sumo-Bloods prefer padded armor for canal work.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Medium Armor", "description": "Hide (AC 12 + DEX max 2), Chain Shirt (AC 13 + DEX max 2), Scale Mail (AC 14 + DEX max 2, stealth disadvantage), Breastplate (AC 14 + DEX max 2), Half Plate (AC 15 + DEX max 2, stealth disadvantage). In Solis-Grave: House Pyre forges half plate. House Ferrum crafts scale mail from drake scales.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Heavy Armor", "description": "Ring Mail (AC 14, stealth disadvantage), Chain Mail (AC 16, STR 13, stealth disadvantage), Splint (AC 17, STR 15, stealth disadvantage), Plate (AC 18, STR 15, stealth disadvantage). In Solis-Grave: House Ferrum produces the finest plate armor in the continent. A full set of Ferrum Iron-Bound Plate costs 1,500 GC and can stop a wyvern's claw.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Shields", "description": "Shield (+2 AC, requires one hand to wield). In Solis-Grave: House Ferrum tower shields are standard issue for border legion infantry. Vortex bucklers provide +1 AC and can be donned or doffed as a free action.", "source_tags": ["solis-grave","5e","srd"]},

    # MOUNTS & VEHICLES
    {"category": "equipment", "name": "Standard Mounts", "description": "Draft Horse (50 GC, speed 40 ft, carrying capacity 540 lbs), Riding Horse (75 GC, speed 60 ft, capacity 480 lbs), Pony (30 GC, speed 40 ft, capacity 225 lbs), Warhorse (400 GC, speed 60 ft, capacity 540 lbs, trained for combat). In Solis-Grave: Warhorses must pass WIS save vs Sovereign aura or cower. House Ferrum breeds the finest warhorses.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Exotic Mounts", "description": "Camel (50 GC, speed 50 ft, capacity 480 lbs, desert-adapted), Elephant (200 GC, speed 40 ft, capacity 1,320 lbs), Mastiff (25 GC, speed 40 ft, capacity 195 lbs, Medium rider only). In Solis-Grave: domesticated baggage-drakes serve as heavy cargo mounts. Wyverns can be tamed by Sovereign-class purity only.", "source_tags": ["solis-grave","5e","srd"]},
    {"category": "equipment", "name": "Land Vehicles", "description": "Cart (15 GC, capacity 200 lbs), Wagon (35 GC, capacity 400 lbs, 2 draft animals), Carriage (100 GC, capacity 600 lbs), Sled (20 GC, capacity 300 lbs). In Solis-Grave: House Ferrum armored wagons patrol the border roads. Citadel supply carts run between the academy and the lower markets.", "source_tags": ["solis-grave","5e","srd"]},
]

# Insert all rules
count = 0
for r in rules:
    cols = ', '.join(r.keys())
    placeholders = ', '.join(['%s']*len(r))
    vals = [json.dumps(v) if isinstance(v, list) else v for v in r.values()]
    try:
        cur.execute(f"INSERT INTO compendium_rules ({cols}) VALUES ({placeholders}) ON CONFLICT DO NOTHING", vals)
        count += 1
    except Exception as e:
        if count < 3: print(f"  Skip {r['name']}: {e}")

cur.execute("SELECT count(*) FROM compendium_rules")
print(f"Rules: {cur.fetchone()[0]} total (added {count})")

# Create custom_classes table
cur.execute("""
CREATE TABLE IF NOT EXISTS custom_classes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID,
    name TEXT NOT NULL,
    created_by TEXT, description TEXT, inspiration TEXT,
    hit_die INTEGER, proficiencies JSONB, saving_throws JSONB,
    features JSONB, subclasses JSONB,
    purity_required INTEGER DEFAULT 0, spellcasting BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
)
""")
print("custom_classes: table created")

c.close()
print("Done!")
