const STORE_CONFIG = {
    storeName: "Sinister H-Town RP",
    currency: "$",
    tebexStoreUrl: "https://sinister-htown.tebex.io",
    theme: {
        primary: "#BF5700",
        secondary: "#FF8C42",
        background: "#0d0d14",
        surface: "#1a1a2e",
        text: "#e0e0e0",
        muted: "#6b7280",
        success: "#22c55e",
        danger: "#ef4444",
        warning: "#f59e0b",
    },
    categories: [
        { id: "vip", label: "VIP", icon: "crown" },
        { id: "money", label: "Money", icon: "dollar-sign" },
        { id: "vehicles", label: "Vehicles", icon: "car" },
        { id: "items", label: "Items", icon: "shopping-bag" },
        { id: "jobs", label: "Jobs", icon: "briefcase" },
        { id: "gangs", label: "Gangs", icon: "users" },
        { id: "customization", label: "Customization", icon: "edit" },
        { id: "utilities", label: "Utilities", icon: "settings" },
    ],
    apiBase: "",
};
